name: ArrowTrajectory
version: '${project.version}'
main: com.github.tacowasa059.arrow_data.ArrowTrajectoryPlugin
api-version: 1.16
commands:
  arrowtraj:
    description: show the trajectory of a arrow
    usage: /<command> start or /<command> stop